### PR TITLE
Fix support for rmmod

### LINKED ISSUE #1: Support rmmod
Currently, rmmod does not work correctly.

### PR DESCRIPTION
**Pull request by arter97**
Fixes #1.

This PR adds missing resource frees and fixes some deregister code logic so that NVMe doesn't cause an I/O timeout during the rmmod.

This was successfully tested under a system with KASAN and kmemleak enabled. Both didn't report back any memory faults from switching all 4 supported configurations from NVMeVirt without any reboots in between.

### CODE REVIEW

**Comment by arter97** [comment]
The notable exception here is dma.c's `struct ioat_dma_chan *dtc` allocation from ioat_dma_add_channel().

I wasn't able to test it out and the code isn't straightforward enough for me to attempt a blind fix.

So in theory, each rmmod will still leak 40 bytes per each DMA channel, if it is used. I'll leave this up for someone else to fix :)

**Comment by beowulf** [comment]
> The notable exception here is dma.c's `struct ioat_dma_chan *dtc` allocation from ioat_dma_add_channel().
> 
> I wasn't able to test it out and the code isn't straightforward enough for me to attempt a blind fix.
> 
> So in theory, each rmmod will still leak 40 bytes per each DMA channel, if it is used. I'll leave this up for someone else to fix :)

The issue is assigned to @jaehshim in #13.

**Review by beowulf — COMMENTED** [review]
Oh, I didn't know that we can handle the large stack warning this way!

**Comment by beowulf** [comment]
@arter97 Thanks for PR handling the rmmod (finally!) and #1. Great!

**Pull request merged**
